#cloud-config
users:
  - default
  - name: munge
    uid: 1001
  - name: slurm
    uid: 1002

timezone: Europa/Budapest

ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - time.kfki.hu

packages:
  - libmysqlclient-dev
  - mariadb-server
  - ntp
  - nfs-kernel-server
  - htop
  - mc

write_files:
- path: /tmp/slurmdbd.conf
  content: |
    # Example slurmdbd.conf file.
    #
    # See the slurmdbd.conf man page for more information.
    #
    AuthType=auth/munge
    AuthInfo=/var/run/munge/munge.socket.2
    DbdHost=localhost
    #DbdBackupHost=backup
    StorageHost=localhost
    StorageLoc=slurm_acct_db
    StoragePass=slurmdbpass
    StorageType=accounting_storage/mysql
    StorageUser=slurm
    LogFile=/var/log/slurm-llnl/slurmdbd.log
    PidFile=/run/slurm-llnl/slurmdbd.pid
    #PluginDir=/usr/lib/slurm
    SlurmUser=slurm
    DebugLevel=debug4
  permissions: '755'

- path: /tmp/slurm.conf
  content: |
    # Example slurm.conf file. Please run configurator.html
    # (in doc/html) to build a configuration file customized
    # for your environment.
    #
    #
    # slurm.conf file generated by configurator.html.
    #
    # See the slurm.conf man page for more information.
    #
    ClusterName=compute-cluster
    SlurmctldHost=HOSTNAME(IP)
    SlurmUser=slurm
    AuthType=auth/munge
    StateSaveLocation=/var/spool/slurmctld
    SlurmdSpoolDir=/var/spool/slurmd
    #JobCheckpointDir=/var/lib/slurm-llnl/job_checkpoint
    #SlurmdSpoolDir=/var/lib/slurm-llnl/slurmd
    #StateSaveLocation=/var/lib/slurm-llnl/state_checkpoint
    SwitchType=switch/none
    MpiDefault=none
    SlurmctldPidFile=/run/slurm-llnl/slurmctld.pid
    SlurmdPidFile=/run/slurm-llnl/slurmd.pid
    ProctrackType=proctrack/cgroup
    #PluginDir=/usr/lib/slurm
    ReturnToService=1
    TaskPlugin=task/cgroup
    # TIMERS
    #SlurmctldTimeout=300
    #SlurmdTimeout=300
    #InactiveLimit=0
    #MinJobAge=300
    #KillWait=30
    #Waittime=0
    # SCHEDULING
    SchedulerType=sched/backfill
    SelectType=select/cons_res
    #SelectTypeParameters=CR_Core_Memory,CR_CORE_DEFAULT_DIST_BLOCK,CR_ONE_TASK_PER_CORE
    SelectTypeParameters=CR_Core
    #FastSchedule=2
    # LOGGING
    SlurmctldDebug=debug3
    SlurmctldLogFile=/var/log/slurm-llnl/slurmctld.log
    SlurmdDebug=debug3
    SlurmdLogFile=/var/log/slurm-llnl/slurmd.log
    JobCompType=jobcomp/none
    # ACCOUNTING
    AccountingStorageEnforce=limits
    JobAcctGatherType=jobacct_gather/cgroup
    #JobAcctGatherType=jobacct_gather/linux
    #AccountingStorageTRES=gres/gpu
    DebugFlags=CPU_Bind
    AccountingStorageType=accounting_storage/slurmdbd
    AccountingStorageHost=HOSTNAME
    #AccountingStoragePass=/var/run/munge/global.socket.2
    AccountingStorageUser=slurm
    # COMPUTE NODES
    #GresTypes=gpu
    PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP
  permissions: '755'

- path: /tmp/cgroup.conf
  content: |
    ###
    #
    # Slurm cgroup support configuration file
    #
    # See man slurm.conf and man cgroup.conf for further
    # information on cgroup configuration parameters
    #--
    CgroupAutomount=yes
    ConstrainCores=no
    ConstrainRAMSpace=no
  permissions: '755'

- path: /bin/install-slurm.sh
  content: |
    #!/bin/bash

    set -x

    # Install NFS
    mkdir -p /storage/slurm
    chown -R ubuntu:ubuntu /storage
    echo "/storage *(rw,sync,no_subtree_check)" >> /etc/exports
    systemctl restart nfs-kernel-server

    # Install munge and configure munge
    apt install -y munge=0.5.13-2build1
    cp /etc/munge/munge.key /storage/slurm/munge.key
    chmod 755 /storage/slurm/munge.key
    chown -R munge: /etc/munge/ /var/log/munge/ /var/lib/munge/ /run/munge/
    chmod 0700 /etc/munge/ /var/log/munge/ /var/lib/munge/
    chmod 0755 /run/munge/
    chmod 0600 /etc/munge/munge.key
    chown munge /etc/munge/munge.key
    systemctl enable munge
    systemctl start munge

    # Configure mariadb
    systemctl enable mariadb
    systemctl start mariadb
    mysql -u root -e "create database slurm_acct_db;"
    mysql -u root -e "create user 'slurm'@'localhost';"
    mysql -u root -e "set password for 'slurm'@'localhost' = password('slurmdbpass');"
    mysql -u root -e "grant usage on *.* to 'slurm'@'localhost';"
    mysql -u root -e "grant all privileges on slurm_acct_db.* to 'slurm'@'localhost';"
    mysql -u root -e "flush privileges;"

    # Install slurm and configure slurm
    apt install -y slurmdbd=19.05.5-1
    apt install -y slurmctld=19.05.5-1
    chown ubuntu /etc/slurm-llnl/
    mkdir /var/spool/slurmctld /var/spool/slurmd
    chown slurm:slurm /var/spool/slurmctld /var/spool/slurmd
    chmod 755 /var/spool/slurmctld /var/spool/slurmd
    mkdir /run/slurm-llnl
    chown slurm:slurm /var/log/slurm-llnl /run/slurm-llnl
    chmod 755 /var/log/slurm-llnl /var/run/slurm-llnl
    # SlurmDBD config file
    chown ubuntu:ubuntu /tmp/slurmdbd.conf
    cp /tmp/slurmdbd.conf /etc/slurm-llnl/slurmdbd.conf
    chown ubuntu /etc/slurm-llnl/slurmdbd.conf
    chmod 644 /etc/slurm-llnl/slurmdbd.conf
    sed -i 's*PIDFile=/run/slurmdbd.pid*PIDFile=/run/slurm-llnl/slurmdbd.pid*g' /lib/systemd/system/slurmdbd.service
    sed -i 's*PIDFile=/run/slurmctld.pid*PIDFile=/run/slurm-llnl/slurmctld.pid*g' /lib/systemd/system/slurmctld.service
    HOSTNAME=$(hostname | awk {'print $1'})
    IP=$(hostname -I | awk {'print $1'})
    # Slurm config file
    sed -i s/HOSTNAME/${HOSTNAME}/g /tmp/slurm.conf
    sed -i s/IP/${IP}/g /tmp/slurm.conf
    chown ubuntu:ubuntu /tmp/slurm.conf
    cp /tmp/slurm.conf /etc/slurm-llnl/slurm.conf
    cp /etc/slurm-llnl/slurm.conf /storage/slurm/slurm.conf
    chmod 755 /storage/slurm/slurm.conf
    chown ubuntu:ubuntu /storage/slurm/slurm.conf
    chmod 644 /etc/slurm-llnl/slurm.conf
    # Cgroup file
    chown ubuntu:ubuntu /tmp/cgroup.conf
    cp /tmp/cgroup.conf /etc/slurm-llnl/cgroup.conf
    cp /etc/slurm-llnl/cgroup.conf /storage/slurm/cgroup.conf
    chmod 755 /storage/slurm/cgroup.conf
    chown ubuntu:ubuntu /storage/slurm/cgroup.conf
    chown ubuntu /etc/slurm-llnl/cgroup.conf
    chmod 644 /etc/slurm-llnl/cgroup.conf
    systemctl daemon-reload
    systemctl enable slurmdbd
    systemctl start slurmdbd
    # TODO
    sleep 20
    sacctmgr add -i cluster compute-cluster
    sacctmgr add -i account ubuntu
    sacctmgr add -i user ubuntu DefaultAccount=ubuntu
    systemctl enable slurmctld
    echo "* * * * * root bash /bin/slurm-conf-populator.sh" | tee -a /etc/crontab
    echo "* * * * * root bash /bin/slurm-scale-down.sh" | tee -a /etc/crontab
  permissions: '755'


- path: /bin/slurm-conf-populator.sh
  content: |
    #!/bin/bash

    set -x

    answer=$(cmp --silent /etc/slurm-llnl/slurm.conf /storage/slurm/slurm.conf || echo "different")
    if [[ "$answer" = "different" ]]; then
      cp /storage/slurm/slurm.conf /etc/slurm-llnl/slurm.conf
      chown ubuntu:ubuntu /etc/slurm-llnl/slurm.conf
      chmod 644 /etc/slurm-llnl/slurm.conf
      systemctl daemon-reload
      systemctl restart slurmdbd
      sleep 5
      systemctl restart slurmctld
    fi
  permissions: '744'

- path: /bin/slurm-scale-down.sh
  content: |
    #!/bin/bash

    set -x

    LOG_LOCATION=/home/ubuntu/downscale.log
    exec 3>&1 4>&2
    trap 'exec 2>&4 1>&3' 0 1 2 3
    exec 1>>$LOG_LOCATION 2>&1

    echo "####"
    date
    WORKARR=(`sinfo -dh | col6 | sed 's/,/ /'`)
    for i in ${!WORKARR[@]}
      do
        date
        echo "##REMOVE FROM THE CLUSTER: ${WORKARR[i]} ##"
        su - ubuntu -c "grep -v "${WORKARR[i]}" /storage/slurm/slurm.conf > /storage/slurm/slurm2.conf"
        su - ubuntu -c "mv /storage/slurm/slurm2.conf /storage/slurm/slurm.conf"
      done
    echo "####"
  permissions: '744'

runcmd:
- /bin/install-slurm.sh